// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    flash_borrower
    (
        init => init
        upgrade => upgrade
        configProfitGeneratorAddress => config_profit_generator_address
        profitGenerator => profit_generator
        profitGeneratorRepayFraction => profit_generator_repay_fraction
        profitGeneratorRepayWithoutFees => profit_generator_repay_without_fees
        profitGeneratorNoRepayment => profit_generator_no_repayment
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
