// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    flash_loan
    (
        init => init
        upgrade => upgrade
        flashLoan => flash_loan
        flashLoanConfig => flash_loan_config
        repayLoan => repay_loan
        getMaxLoan => get_max_loan
        getMinLoan => min_loan_amount
        getFeeBasisPoints => fee_basis_points
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
